casper_scripts/components/crm-error.js
casper_scripts/page-objects/crm-page.js
casper_scripts/page-objects/form-page.js
scenarios/components.json

This PR adds a new scenario aimed at specific CiviCRM HTML components. The first of these components is the `crm-error` element.
* This commit https://github.com/compucorp/backstopjs-config/pull/1/commits/5b03d59645e17f4d9c25f85684e311ac7cc1f0f8 updates the **crm-page.js** and **form-page.js** page objects so they follow the style guide.
* A **submit** method was added on **form-page.js**:
```js
submit: {
value: function () {
this.clickFirst('#content form .crm-form-submit');
}
}
```
And to use it you can do this `formPage.submit()`.
This method will only submit the main form inside the page and ignore any other forms such as the contact search, etc.
* A **waitForUrlChange** method was added to **crm-page.js**:
```js
waitForUrlChange: function () {
var oldUrl = …
```

PCHR-2545: Add missing component scenarios

---

README.md
scenarios/administer-menu.json
scenarios/components.json
scenarios/contributions-menu.json
scenarios/events-menu.json
scenarios/mailings-menu.json
scenarios/membership-menu.json

This PR adds missing scenarios to get all pages tested when running BackstopJS tests.
https://github.com/compucorp/backstopjs-config/pull/3/commits/bfd7b3f00b09d6ab4c9a7d9000ed130df9aa554d changes path for testing error component to `/civicrm/group/add?reset=1` instead of calling L&A path `/civicrm/admin/leaveandabsences/periods?action=add&reset=1` which is not a part of vanilla CiviCRM
https://github.com/compucorp/backstopjs-config/pull/3/commits/efbf673739635b42de5dfa69b599f12b66b0217e new scenarios which are part of default CiviCRM installation.
We are updating README.md file to add new screens in the list

NDI-32: Added missing scenarios of vanilla CiviCRM

---

test-runner.js

Previously Backstop JS had to be installed globally to run the test suite.
Changed to code to use local copy of Backstop JS instead.

PCHR-3435: Use local backstop

---

casper_scripts/administer-menu/connections.js
casper_scripts/administer-menu/edit-multiple-choice-options.js
casper_scripts/administer-menu/system-status.js
casper_scripts/common/close-notifications.js
casper_scripts/contact-page/record-event.js
casper_scripts/contact-page/record-membership.js
casper_scripts/contact-page/show-contributions.js
casper_scripts/contact/add-tag-set.js
casper_scripts/contact/add-tag.js
casper_scripts/contact/manage-groups.js
casper_scripts/contributions/new-pledge-filters.js
casper_scripts/contributions/new-pledge-sorting.js
casper_scripts/mailings/attachments.js
casper_scripts/mailings/mailing.js
casper_scripts/mailings/message-workflow.js
casper_scripts/mailings/publication.js
casper_scripts/mailings/responses.js
casper_scripts/mailings/tracking.js
casper_scripts/membership/search-result.js
casper_scripts/page-objects/crm-page.js
casper_scripts/page-objects/form-page.js
casper_scripts/search/actions/email-schedule-attachments.js
casper_scripts/search/actions/email-schedule-header-footer.js
casper_scripts/search/actions/email-schedule-publication.js
casper_scripts/search/actions/email-schedule-responses.js
casper_scripts/search/actions/email-schedule-tracking.js
scenarios/administer-menu.json
scenarios/components.json
scenarios/contact-menu.json
scenarios/mailings-menu.json

Some of the scenarios relied on markup that is present only when the CiviCRM admin is using Drupal's "seven" theme, leading the erroneous results when using a different admin theme (for example, "Bartik").
This PR removes any "Seven" dependency and also fixes scenarios that #5 missed
The `FormPage` object has a `submit`, which used this selector to find the "submit" button in a form
```css
#content form .crm-form-submit
```
There were two problems with this selector
1. The `#content` id exists only in the "Seven" theme
2. The class `.crm-form-submit` is applied not only to the submit button, but also to the cancel button. The only reason that the cancel button was never clicked is simply because the submit button comes first in the markup
Given the above, the selector had been changed to …

NDI-85: Remove "seven" dependency

---

scenarios/search-menu.json

* Full-text Search Results - Contacts
* Full-text Search Results - Activities
* Full-text Search Results - Contributions
* Full-text Search Results - Event Participants
* Full-text Search Results - Memberships
```shell
$ gulp backstopjs:reference --group search-menu && gulp backstopjs:test --group search-menu
```

SHOR-27: Add screens for Full text search and internal pages

---

backstop_data/engine_scripts/puppet/search/search-builder-results.js
scenarios/search-menu.json

* Search Builder Result screen.
```shell
$ gulp backstopjs:reference --group search-menu && gulp backstopjs:test --group search-menu
```

SHOR-29: Add missing screens for Search builder result screen

---

backstop_data/engine_scripts/puppet/dashboard/configure-dashboard.js
backstop_data/engine_scripts/puppet/mailings/ab-test-manage.js
scenarios/dashboard.json

* Screen for Home Dashboard Screen
* Configure dashboard Dashboard
* Added a new group `home-dashboard` to the scenarios group list.
```shell
$ gulp backstopjs:reference --group home-dashboard && gulp backstopjs:test --group home-dashboard
```

SHOR-26: Add missing screens for Home/Dashboard and Configure Dashboard screen

---

backstop_data/engine_scripts/puppet/membership/find-memberships-delete.js
backstop_data/engine_scripts/puppet/membership/find-memberships-edit.js
backstop_data/engine_scripts/puppet/membership/find-memberships-renew-cc.js
backstop_data/engine_scripts/puppet/membership/find-memberships-renew.js
backstop_data/engine_scripts/puppet/membership/find-memberships-view.js
scenarios/membership-menu.json

* Search - Find Memberships Results - Delete Modal
* Search - Find Memberships Results - Renew Modal
* Search - Find Memberships Results - Renew-Credit Card Modal
* Search - Find Memberships Results - Edit Modal
* Search - Find Memberships Results - View Modal
```shell
$ gulp backstopjs:reference --group search-menu && gulp backstopjs:test --group search-menu
```

SHOR-30: Add missing screens for Find memberships screens

---

backstop_data/engine_scripts/puppet/search/find-activities-delete-modal.js
backstop_data/engine_scripts/puppet/search/find-activities-edit-modal.js
backstop_data/engine_scripts/puppet/search/find-activities-view-modal.js
backstop_data/engine_scripts/puppet/search/find-participants-delete-modal.js
backstop_data/engine_scripts/puppet/search/find-participants-edit-modal.js
backstop_data/engine_scripts/puppet/search/find-participants-view-modal.js
scenarios/search-menu.json

* Search - Find Participants Results - View Modal
* Search - Find Participants Results - Edit Modal
* Search - Find Participants Results - Delete Modal
* Search - Find Activities Results - View
* Search - Find Activities Results - Edit
* Search - Find Activities Results - Delete
```shell
$ gulp backstopjs:reference --group search-menu && gulp backstopjs:test --group search-menu
```

SHOR-31: Add missing screens for find participants and find activities screens

---

backstop_data/engine_scripts/puppet/search/actions/common.js
backstop_data/engine_scripts/puppet/search/actions/merge-contacts.js
backstop_data/engine_scripts/puppet/search/find-activities-delete-modal.js
scenarios/contact-page.json

This PR contains some minor JS fixes for backstop test suite to work seamless with Default Vanilla CiviCRM (enabled with sample data).
Fixes following technical issues.
In Find activity Search result page, the action link delete for vanilla civiCRM comes directly on the right. But because of civicase Component was enabled the delete button comes under the 3 dot menu dropdown on the right and the test case was written for that condition.
Removed the JS interaction code to open the dropdown so that it directly opens the delete modal.
In Sample data there are no organisation that contains 'Technology' as keyword and hence backstop fails
Removing the the 'Technology' keyword from the search filter while searching. see (puppet/search/actions/common.js). Also updated the Checkbox Ids for …

SHOR-52: Fix markup for JS backstop test suite

---

README.md
backstop_data/engine_scripts/puppet/search/actions/common.js
backstop_data/engine_scripts/puppet/search/actions/email-schedule.js

* Parallel capture limit fix and schedule email issue fixes.
* Update readme with Drupal user name requirement.
When running backstop with parallel captures upto 5, `search-actions` group tests fails with some errors because sometimes contact search form on clicking on search results redirects to advance search rather than results page.
After having it discussed with the civicrm dev team, we discovered that civicrm is invalidating `qf_key` parameter as the same page is accessed with different Drupal login sessions with multiple `qf_keys` passed.
Dev channel discussion thread 
-  https://chat.civicrm.org/civicrm/pl/q85ts7uu3ffqmmktaawcgrhyrr
Through backstop we are checking if the page is being redirected to the advance search and if yes then we refill the advance search form with the same …

SHOR-57: Parallel capture limit fix and Schedule Email issue fix

---

backstop_data/backstop.tpl.json
backstop_data/engine_scripts/puppet/contact/add-tag.js
backstop_data/engine_scripts/puppet/contact/clone-tags-modal.js
backstop_data/engine_scripts/puppet/contact/delete-tags-modal.js
scenarios/contact-page.json

This PR adds some miscellaneous improvements and fixes to the test suite
The screenshots of the modals were taken by cropping around the `.ui-dialog` element (the outermost element of a modal.  This unfortunately caused BackstopJS not to spot that an entire portion of the modal was missing, like in the case of https://github.com/civicrm/org.civicrm.shoreditch/pull/272
By taking a screenshot of the whole page instead of cropping it, the issue is correctly detected
This selector
```css
a[href^="/civicrm/tag/edit?action=add"]
```
was used in 3 scenarios: 
* Tags - Add Tag
* Tags - Clone Tags
* Tags - Delete Tags Modal
and all would be fail if the site BackstopJS was browsing would be in a sub-folder, because the selector would not much the `href` of the button anymore
Example
url: …

SHOR-58: Misc improvements and fixes

---

package-lock.json
package.json

Upgrading backstopjs to the latest version available, which solves a security vulnerability issues in one of its dependencies

PCHR-4427: Upgrade to backstopjs@3.8.5

---

README.md
backstop_data/engine_scripts/puppet/contributions/new-tab-completed-contribution.js
backstop_data/engine_scripts/puppet/contributions/new-tab-pending-contribution.js
backstop_data/engine_scripts/puppet/contributions/new-tab-view-pledge.js
backstop_data/engine_scripts/puppet/events/new-tab-view-events.js
backstop_data/engine_scripts/puppet/page-objects/crm-page.js
scenarios/contributions-menu.json
scenarios/events-menu.json

This PR adds following screens to the backstopjs test suite in a new page (non modal)
* Contributions - Completed contributions
* Contributions - Pending contributions
* Contributions - View pledge
* Events - View events
These pages need to be opened in a new page as these actually open as modals. To handle this generically a new page function `openInNewTab` is created.
This gets the href from the anchor selector and open the page in the same tab. This mimics opening in a new tab. See backstop_data/engine_scripts/puppet/page-objects/crm-page.js

SE-7: Add pages to be opened in new tab for view pledge, contributions and event

---

.github/workflows/backstop.yml
README.md

As part of this PR, Now support for multiple CiviCRM versions are added. That means different CiviCRM versions can be selected as Reference/Test while comparing screenshots.
`.github/workflows/backstop.yml` has been updated.
Now we create 2 sites, to achieve the above mentioned requirement.

CPS-393: Support for multiple CiviCRM versions

---

.github/workflows/backstop.yml

This PR fixes the Git clone statement, which caused the Backstop Js Github Action to fail.
Replaced `git clone <repository_url> depth=1` with `git clone <repository_url> --depth 1`.

CPS-393: Fix Git clone statement

---

.github/workflows/backstop.yml
backstop_data/backstop.tpl.json
gulp-tasks/backstop.js
package-lock.json
package.json

This PR makes some updates to Backstop JS suite to make it more reliable.
1. Decreased `asyncCaptureLimit` to 1, which is more reliable.
2. Added `1000` as the default timeout, this also increases reliability.
3. Updated backstopjs to latest 5.1.0, which uses Pupeteer 7.1.0, instead of previous version which used Pupeteer 1.15.0.

CPS-393: Update BackstopJS version

---

.github/workflows/backstop.yml

The shoreditch branches does not include the CSS files. So this PR generates them before running the Backstop tests so that backstop can use the compiled CSS.
Not needed
Added the following steps before running Backstop test
```
npm install
npx gulp sass
```

CPS-393: Generate CSS files on the fly

---

.github/workflows/backstop.yml

In the previous PR https://github.com/compucorp/backstopjs-config/pull/48, the step to move inside the Shoreditch folder was missing. This PR fixes that.
Not needed
Added the following steps before running `npm install`
```
cd org.civicrm.shoreditch
```

CPS-393: Fix Github Action

---

.github/workflows/backstop.yml

Backstop JS Github Action was not working after https://github.com/compucorp/backstopjs-config/pull/50. Because correct node version was not installed before installing shoreditch.
Tested that its working fine https://github.com/compucorp/backstopjs-config/actions/runs/751000264

CATL-1660: Fix github action
